.Dd $Mdocdate$
.Dt PINGPATH 1 URM
.Os
.Sh NAME
.Nm pingpath
.Nd a system ping wrapper for network diagnostic
.Sh SYNOPSIS
.Nm
.Op Fl chiInpqsStv46
.Sy [ TARGET ]
.Sh DESCRIPTION
A network diagnostic tool based on parsing system
.Sy ping
output with functionality of
.Sy traceroute ,
.br
No need set-root-uid or raw-socket-perms itself to run due to being a wrapper for ping.
.br
Inspired by ncurses look of
.Sy mtr
and written in
.Sy GTK4 .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c, Fl -cycles Ar NUMBER
Run
.Ar number
of cycles per target
.br
Default 100
.It Fl i, Fl -interval Ar SECONDS
Interval in
.Ar seconds
between pings
.br
Default 1
.It Fl n, Fl -numeric
Numeric output (i.e. disable DNS resolving)
.br
Default: DNS is enabled
.It Fl p, Fl -payload Ar PATTERN
Payload
in hex notation, upto 16 bytes (32 hex characters)
.It Fl q, Fl -qos Ar BITS
QoS/ToS
.Ar byte
(0..255) in outgoing pings
.It Fl s, Fl -size Ar BYTES
Payload
.Ar size ,
minimum is 16 (timestamp size), maximum is 9000-20-8
.br
Default 56
.It Fl t, Fl -ttl Ar MIN,MAX
TTL
.Ar range
to ping, it can be partially set as
.Ar MIN
or as
.Ar MIN,MAX
or as
.Ar ,MAX
too
.br
Default 1,30
.It Fl I, Fl -info Ar KEYS
Hop info elements which match [hacdr] pattern
.br
Keys stand for: Host AS CC Description Route
.br
Default: hac
.It Fl S, Fl -stat Ar KEYS
Display statistic elements which match [lsrmbwaj] pattern
.br
Keys stand for: Loss Sent Received Last(Msec) Best Worst Average Jitter
.br
Default: lsmbwaj
.It Fl v, Fl -verbose Ar LEVEL
Print debug messages to stdout according to
.Ar level
.Bl -tag -offset Ds
.br
.Sy any bit
log to stdout
.br
.Sy 2nd bit 
common debug
.br
.Sy 3rd bit
dns debug
.br
.Sy 4th bit
whois debug
.El
.Bl -tag -width Ds
.It Fl 4, Fl -ipv4
IPv4 only
.It Fl 6, Fl -ipv6
IPv6 only
.Sh KNOWN CAVEATS
RTT for transit hops is calculated from TIMESTAMPS generated by
.Sy ping
for
.Sy no-answer-yet
and
.Sy time-to-live-exceeded
diagnostic messages, so that use
.Sy traceroute
or
.Sy mtr
for more accurate statistics of transit hops
.El
.Sh PROJECT LOCATION
.Lk https://github.com/yvs2014/pingpath
.El
.Sh SEE ALSO
ping(8), traceroute(8), mtr(8)
