.Dd $Mdocdate$
.Dt PINGPATH 1 URM
.Os
.Sh NAME
.Nm pingpath
.Nd ping wrapper for network diagnostic
.Sh SYNOPSIS
.Nm
.Op Fl chigInpqsStv46
.Sy [ TARGET ]
.Sh DESCRIPTION
Network diagnostic tool based on parsing system
.Sy ping
output with functionality of
.Sy traceroute .
.br
No need set-root-uid or raw-socket-perms itself to run due to being a wrapper for ping.
.br
Inspired by ncurses look of
.Sy mtr
and written in
.Sy GTK4 .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c, Fl -cycles Ar NUMBER
Run
.Ar number
of cycles per target.
.br
Default
.Ar 100
.It Fl i, Fl -interval Ar SECONDS
Interval in
.Ar seconds
between pings.
.br
Default
.Ar 1
.It Fl n, Fl -numeric
Numeric output (i.e. disable DNS resolving).
.br
Default
.Ar symbolic
.It Fl p, Fl -payload Ar PATTERN
Payload
in hex notation, upto 16 bytes (32 hex characters).
.br
Default
.Ar 00
.It Fl q, Fl -qos Ar BITS
QoS/ToS
.Ar byte
(0..255) in outgoing pings.
.br
Default
.Ar 0
.It Fl s, Fl -size Ar BYTES
Payload
.Ar size ,
minimum is 16 (timestamp size), maximum is 9000-20-8.
.br
Default
.Ar 56
.It Fl t, Fl -ttl Ar MIN,MAX
TTL
.Ar range
to ping, it can be partially set as
.Ar MIN
or
.Ar MIN,MAX
or
.Ar ,MAX
.br
Default
.Ar 1,30
.It Fl I, Fl -info Ar KEYS
Hop info elements which match
.Ar hacdr
pattern.
.br
Keys stand for:
.Bl -tag -offset Ds -compact
.It Cm h
Host
.It Cm a
AS
.It Cm c
CC
.It Cm d
Description
.It Cm r
Route
.El
Default
.Ar hac
.El
.Bl -tag -width Ds
.It Fl S, Fl -stat Ar KEYS
Display statistic elements which match
.Ar lsrmbwaj
pattern.
.br
Keys stand for:
.Bl -tag -offset Ds -compact
.It Cm l
Loss
.It Cm s
Sent
.It Cm r
Received
.It Cm m
Last(Msec)
.It Cm b
Best
.It Cm w
Worst
.It Cm a
Average
.It Cm j
Jitter
.El
Default
.Ar lsmbwaj
.El
.Bl -tag -width Ds
.It Fl g, Fl -graph Ar TYPE
Draw graphs of
.Ar type :
.Bl -tag -offset Ds -compact
.It Cm 0
none
.It Cm 1
just dots
.It Cm 2
straight line
.It Cm 3
curved spline
.El
Default
.Ar 3
.El
.Bl -tag -width Ds
.It Fl v, Fl -verbose Ar LEVEL
Print debug messages to stdout according to bits of
.Ar level :
.Bl -tag -offset Ds -compact
.It Cm any
log to stdout
.It Cm 2nd
common debug
.It Cm 3rd
dns debug
.It Cm 4th
whois debug
.El
Default
.Ar none
.El
.Bl -tag -width Ds
.It Fl 4, Fl -ipv4
IPv4 only
.It Fl 6, Fl -ipv6
IPv6 only
.El
.Sh KEYBOARD SHORTCUTS
For common actions:
.Bl -tag -offset Ds -compact
.It Cm Ctrl+S
Start/Stop pings
.It Cm Space
Pause/Resume visual updates
.It Cm Ctrl+R
Reset statistics
.It Cm Ctrl+L
Toggle graph legend on/off
.It Cm Ctrl+H
Display help
.It Cm Ctrl+X
Exit
.El
.Bl -tag -width Ds
.Sh KNOWN CAVEATS
RTT for transit hops is calculated from TIMESTAMPS generated by
.Sy ping
for
.Sy no-answer-yet
and
.Sy time-to-live-exceeded
diagnostic messages.
Jitter used here is the simple average difference between two consecutive RTTs for depicting the range in which they vary.
So that use
.Sy traceroute
or
.Sy mtr
for more accurate measures of transit hops and statistics.
.El
.Sh PROJECT LOCATION
.Lk https://github.com/yvs2014/pingpath
.El
.Sh SEE ALSO
ping(8), traceroute(8), mtr(8)
