
name: pingpath
base: core22
version: 0.3.13
summary: ping wrapper for network diagnostic
description: |
  Network diagnostic tool based on parsing iputils 'ping' output with functionality of 'traceroute'.
  Inspired by ncurses look of 'mtr' and written in 'GTK4'.

architectures:
  - build-on: [amd64]
  - build-on: [arm64]
  - build-on: [armhf]
#  - build-on: [ppc64el]
#  - build-on: [s390x]
#  - build-on: [riscv64]
grade: stable
confinement: strict

apps:
  pingpath:  # with 3D plots and 2D graphs
    extensions: [gnome]
    command: usr/bin/pingpath
    plugs:
      - network
      - network-observe # for system 'ping' tool
      - network-status  # for whois requests
  pingpath2: # with 2D graphs
    extensions: [gnome]
    command: usr/bin/pingpath2
    plugs:
      - network
      - network-observe # for system 'ping' tool
      - network-status  # for whois requests

parts:
  pingpath:
    plugin: make
#    source-type: local
#    source: .
    source-type: git
    source: https://github.com/yvs2014/pingpath
    source-depth: 1
    build-packages:
      - build-essential
      - pkgconf
      - libgl-dev
      - libepoxy-dev
      - libcglm-dev
    build-environment:
      - PREFIX: /usr
    stage-packages:
      - iputils-ping
      - libgl1
      - libepoxy0
      - libcglm0
    prime:
      - usr/bin/pingpath
      - usr/bin/pingpath2
      - usr/share/man/man1/pingpath.1.gz
      - usr/share/doc/pingpath/examples/pingpath.conf

