
name: pingpath
base: core24
version: 0.3
adopt-info: pingpath
icon: assets/icons/pingpath.svg
summary: ping wrapper for network diagnostic
description: |
  Network diagnostic tool based on parsing iputils 'ping' output with functionality of 'traceroute'.
  Inspired by ncurses look of 'mtr' and written in 'GTK4'.

platforms:
  amd64:
  arm64:
  armhf:
grade: stable
confinement: strict

apps:
  pingpath:
    extensions: [gnome]
    command: usr/bin/pingpath
    desktop: usr/share/applications/net.tools.pingpath.desktop
    plugs:
      - network
      - network-observe # for system 'ping' tool
      - network-status  # for whois requests

parts:
  pingpath:
    plugin: meson
    meson-parameters:
      - --buildtype=release
      - --prefix=/usr
      - --strip
    source: https://github.com/yvs2014/pingpath.git
    override-pull: |
      craftctl default
      craftctl set version="$(craftctl get version).$(git rev-list --count d3da356..HEAD)"
      _ICODIR="/usr/share/icons/hicolor/scalable/apps"
      _SEDEXP="s|Icon=pingpath|Icon=$_ICODIR/pingpath.svg|"
      sed -i "$_SEDEXP" assets/pingpath.desktop
    build-packages:
      - git
      - build-essential
      - pkgconf
      - gettext
      - libgl-dev
      - libepoxy-dev
      - libcglm-dev
    prime:
      - usr/bin/pingpath
      - usr/share/man/man1/pingpath.1*
      - usr/share/doc/pingpath/examples/pingpath.conf
      - usr/share/applications/net.tools.pingpath.desktop
      - usr/share/icons/hicolor/scalable/apps/pingpath.svg
      - usr/share/locale/es/LC_MESSAGES/pingpath.mo
      - usr/share/locale/uk/LC_MESSAGES/pingpath.mo

