
name: pingpath
base: core24
version: 0.3.18
summary: ping wrapper for network diagnostic
description: |
  Network diagnostic tool based on parsing iputils 'ping' output with functionality of 'traceroute'.
  Inspired by ncurses look of 'mtr' and written in 'GTK4'.

platforms:
  amd64:
  arm64:
  armhf:
grade: stable
confinement: strict

apps:
  pingpath:  # with 3D plots and 2D graphs
    extensions: [gnome]
    command: usr/bin/pingpath
    plugs:
      - network
      - network-observe # for system 'ping' tool
      - network-status  # for whois requests
  pingpath2: # with 2D graphs
    extensions: [gnome]
    command: usr/bin/pingpath2
    plugs:
      - network
      - network-observe # for system 'ping' tool
      - network-status  # for whois requests

parts:
  pingpath:
    plugin: make
#    source: .
    source: https://github.com/yvs2014/pingpath.git
    build-packages:
      - build-essential
      - pkgconf
      - libgl-dev
      - libepoxy-dev
      - libcglm-dev
    build-environment:
      - PREFIX: /usr
    stage-packages:
      - iputils-ping
    prime:
      - usr/bin/pingpath
      - usr/bin/pingpath2
      - usr/share/man/man1/pingpath.1.gz
      - usr/share/doc/pingpath/examples/pingpath.conf
      - usr/share/icons/hicolor/scalable/apps/pingpath.svg

