name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_deb_and_run_once:
    name: Build, pack, install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev debhelper pkg-config libgtk-4-dev libjson-glib-dev libgl-dev libepoxy-dev libcglm-dev
      - name: Create .deb package
        run: |
          misc/build_deb.sh
          sudo dpkg -i debs/pingpath_*_*.deb
      - name: Test run
        run: |
          pingpath -V
          pingpath -c 10 -r t 127.0.0.1
      - uses: actions/upload-artifact@v4
        with:
          name: auto-built-pingpath-deb
          path: debs/pingpath_*_*.deb

